### ISSUE TITLE
RangeError: Maximum call stack size exceeded while ( run with ts-node)

### ISSUE THREAD

**Issue by superchaoran** [lijiarui/websocket-api#1]
Running in Mac environment.

First added a 
tsconfig.json, leveled with example folder.
```
{
  "compilerOptions": {
    "lib": [ "es2015" ]
  }
}
```
![image](https://user-images.githubusercontent.com/7088689/30196946-0cf68584-942a-11e7-847c-e48b433023c5.png)

using:
const authKey = '8EB0BF9F-C115-462E-B387-75E54B2376EB'
const account = 'sfsuqun'
for connect.ts

Then build and run the project with:

apt install npm
brew install node
npm install
npm install -g typescript
npm install -g ts-node
ts-node example/connect.ts

Encounter an error:
```
/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:35
  botWs.on('error', function Error(error) {
                    ^
RangeError: Maximum call stack size exceeded
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:35:21)
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:36:11)
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:36:11)
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:36:11)
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:36:11)
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:36:11)
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:36:11)
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:36:11)
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:36:11)
    at Error (/Users/chaoran/Desktop/websocket-api-chaoran/example/connect.ts:36:11)
```

**Comment by lijiarui** [comment]
my tsconfig file:
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "dist",
        "declaration": true,
        "sourceMap": true,
        "noEmitOnError": true,
        "noUnusedLocals": false,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "strictNullChecks": true,
        "noImplicitAny": false,
        "noUnusedParameters": false,
        "noImplicitThis": false,
        "allowUnusedLabels": true,
        "allowJs": true
    },
    "exclude": [
        "node_modules",
        "dist"
    ],
    "include": [
        "src/**/*.ts",
        "bot/**/*.ts"
    ]
}
```
